[package]
name = "password-philosophy"
version = "0.1.0"
authors = ["Sergio Siccha <sergio.siccha@posteo.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
